# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dataretriever_pb2 as dataretriever__pb2


class DataRetrieverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingDomain = channel.unary_unary(
                '/DataRetriever/PingDomain',
                request_serializer=dataretriever__pb2.PingRequest.SerializeToString,
                response_deserializer=dataretriever__pb2.Status.FromString,
                )


class DataRetrieverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataRetrieverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.PingDomain,
                    request_deserializer=dataretriever__pb2.PingRequest.FromString,
                    response_serializer=dataretriever__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataRetriever', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataRetriever(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataRetriever/PingDomain',
            dataretriever__pb2.PingRequest.SerializeToString,
            dataretriever__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
