# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataretriever.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61taretriever.proto\"\x1d\n\x0bPingRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04okay\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t26\n\rDataRetriever\x12%\n\nPingDomain\x12\x0c.PingRequest\x1a\x07.Status\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataretriever_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=23
  _PINGREQUEST._serialized_end=52
  _STATUS._serialized_start=54
  _STATUS._serialized_end=93
  _DATARETRIEVER._serialized_start=95
  _DATARETRIEVER._serialized_end=149
# @@protoc_insertion_point(module_scope)
