# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x04ping\",\n\x0c\x43\x61lculateSum\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\"#\n\x06RetSum\x12\x0c\n\x04okay\x18\x01 \x01(\x08\x12\x0b\n\x03sum\x18\x02 \x01(\x01\"\x1d\n\x0bPingRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04okay\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2E\n\rWhistleblower\x12\x34\n\x10SumResponseTimes\x12\x12.ping.CalculateSum\x1a\x0c.ping.RetSum2>\n\rDataRetriever\x12-\n\nPingDomain\x12\x11.ping.PingRequest\x1a\x0c.ping.Statusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATESUM._serialized_start=20
  _CALCULATESUM._serialized_end=64
  _RETSUM._serialized_start=66
  _RETSUM._serialized_end=101
  _PINGREQUEST._serialized_start=103
  _PINGREQUEST._serialized_end=132
  _STATUS._serialized_start=134
  _STATUS._serialized_end=173
  _WHISTLEBLOWER._serialized_start=175
  _WHISTLEBLOWER._serialized_end=244
  _DATARETRIEVER._serialized_start=246
  _DATARETRIEVER._serialized_end=308
# @@protoc_insertion_point(module_scope)
