name: Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      DATARETRIEVER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DATARETRIEVER_APP_NAME }}:latest
      WHISTLEBLOWER_IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_WHISTLEBLOWER_APP_NAME }}:latest
    steps:
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build dataretriever docker
        run: chmod +x scripts/build-docker.sh && ./scripts/build-docker.sh dataretriever $DATARETRIEVER_IMAGE_NAME
        shell: bash

      - name: Deploy dataretriever docker
        run: chmod +x scripts/deploy.sh && ./scripts/deploy.sh ${{ secrets.GCP_DATARETRIEVER_APP_NAME }} $DATARETRIEVER_IMAGE_NAME
        shell: bash

      - name: Build whistleblower docker
        run: chmod +x scripts/build-docker.sh && ./scripts/build-docker.sh whistleblower $WHISTLEBLOWER_IMAGE_NAME
        shell: bash

      - name: Deploy whistleblower docker
        run: chmod +x scripts/deploy.sh && ./scripts/deploy.sh ${{ secrets.GCP_WHISTLEBLOWER_APP_NAME }} $WHISTLEBLOWER_IMAGE_NAME
        shell: bash

      # - name: Create whistleblower pubsub topic
      #   run: gcloud pubsub topics create whistleblower-topic
      - name: Create whistleblower pubsub topic
        run: chmod +x scripts/create-topic-nofail.sh && ./scripts/create-topic-nofail.sh ${{ secrets.GCP_WHISTLEBLOWER_TOPIC }}
        shell: bash

      # - name: Create whislteblower pubsub subscription
      #   run: gcloud pubsub subscriptions create ${{ secrets.GCP_WHISTLEBLOWER_SUBSCRIPTION }} \
      #        --topic=${{ secrets.GCP_WHISTLEBLOWER_TOPIC }} \
      #        --push-endpoint=${{ secrets.GCP_WHISTLEBLOWER_APP_ENDPOINT }}

# gcloud projects add-iam-policy-binding cloud-run-grpc-ping --member=serviceAccount:k-jonak@cloud-run-grpc-ping.iam.gserviceaccount.com --role=roles/run.admin

# gcloud projects add-iam-policy-binding cloud-run-grpc-ping --member=serviceAccount:k-jonak@cloud-run-grpc-ping.iam.gserviceaccount.com --role=roles/storage.admin

# gcloud projects add-iam-policy-binding cloud-run-grpc-ping --member=serviceAccount:k-jonak@cloud-run-grpc-ping.iam.gserviceaccount.com --role=roles/iam.serviceAccountUser

# gcloud iam service-accounts keys create key.json --iam-account k-jonak@cloud-run-grpc-ping.iam.gserviceaccount.com